// ─────────────────────────────────────────────────────────────────────────────
// Component Library (Phase 9A) — the production component set, across all 14 categories.
//
// Every component is a declarative spec with a REAL render function that consumes design tokens
// (never a hardcoded colour/size) and reads editable props. Container components render their
// builder children. Registered on import (side-effect). This is the catalogue every surface uses.
// ─────────────────────────────────────────────────────────────────────────────
import React from 'react';
import { tok } from './tokens';
import { registerComponent } from './registry';
import type { ComponentSpec, PropSpec, ComponentCategory, RenderInput } from './types';

// ── prop-spec helpers ──
const t = (key: string, label: string, group = 'Content'): PropSpec => ({ key, label, type: 'text', group });
const lt = (key: string, label: string): PropSpec => ({ key, label, type: 'longtext', group: 'Content' });
const col = (key: string, label: string): PropSpec => ({ key, label, type: 'token', group: 'Colors' });
const bl = (key: string, label: string, group = 'Effects'): PropSpec => ({ key, label, type: 'boolean', group });
const sel = (key: string, label: string, options: string[], group = 'Layout'): PropSpec => ({ key, label, type: 'select', options, group });
const num = (key: string, label: string, group = 'Layout'): PropSpec => ({ key, label, type: 'number', group });
const sp = (key: string, label: string): PropSpec => ({ key, label, type: 'space', group: 'Spacing' });
const url = (key: string, label: string): PropSpec => ({ key, label, type: 'url', group: 'Content' });

// ── render helpers ──
const C = (v: unknown, fb?: string) => tok(String(v ?? ''), fb);              // token / space value
const s = (v: unknown, fb = '') => (v == null ? fb : String(v));               // string value
const b = (v: unknown) => v === true || v === 'true';                          // boolean value
const surface: React.CSSProperties = { background: tok('color.surface'), border: `1px solid ${tok('color.outline')}`, borderRadius: tok('radius.md'), color: tok('color.onSurface') };
const specs: ComponentSpec[] = [];
function C_(spec: ComponentSpec) { specs.push(spec); }
const mk = (
  category: ComponentCategory, id: string, name: string, description: string, icon: string,
  props: PropSpec[], defaultProps: Record<string, unknown>, render: ComponentSpec['render'],
  opts: { container?: boolean; motion?: boolean; role?: string } = {},
) => C_({ id, category, name, description, icon, version: '1.0.0', tags: [category.toLowerCase(), ...name.toLowerCase().split(' ')], container: opts.container, defaultProps, props, responsive: true, motion: opts.motion ?? true, a11y: { role: opts.role, label: name }, render, });

// ═══ LAYOUT ═══
mk('Layout', 'container', 'Container', 'A max-width centered content wrapper.', 'Square', [sp('pad', 'Padding'), col('bg', 'Background'), sel('align', 'Align', ['start', 'center', 'end'])], { pad: 'space.5', bg: 'color.background', align: 'center' },
  ({ props, children }: RenderInput) => <div style={{ width: '100%', maxWidth: 1120, margin: '0 auto', padding: C(props.pad), background: C(props.bg), display: 'flex', flexDirection: 'column', alignItems: s(props.align, 'center') as React.CSSProperties['alignItems'] }}>{children}</div>, { container: true });
mk('Layout', 'section', 'Section', 'A full-width page section band.', 'PanelTop', [sp('pad', 'Padding'), col('bg', 'Background')], { pad: 'space.7', bg: 'color.surface' },
  ({ props, children }: RenderInput) => <section style={{ width: '100%', padding: C(props.pad), background: C(props.bg) }}>{children}</section>, { container: true });
mk('Layout', 'grid', 'Grid', 'A responsive CSS grid.', 'LayoutGrid', [num('cols', 'Columns'), sp('gap', 'Gap')], { cols: 3, gap: 'space.4' },
  ({ props, children }: RenderInput) => <div style={{ display: 'grid', gridTemplateColumns: `repeat(${Number(props.cols) || 3}, 1fr)`, gap: C(props.gap) }}>{children}</div>, { container: true });
mk('Layout', 'flex', 'Flex', 'A flexbox row/column.', 'Columns', [sel('dir', 'Direction', ['row', 'column']), sp('gap', 'Gap'), sel('justify', 'Justify', ['flex-start', 'center', 'flex-end', 'space-between'])], { dir: 'row', gap: 'space.3', justify: 'flex-start' },
  ({ props, children }: RenderInput) => <div style={{ display: 'flex', flexDirection: s(props.dir, 'row') as React.CSSProperties['flexDirection'], gap: C(props.gap), justifyContent: s(props.justify, 'flex-start'), flexWrap: 'wrap' }}>{children}</div>, { container: true });
mk('Layout', 'stack', 'Stack', 'A vertical stack with consistent spacing.', 'Rows', [sp('gap', 'Gap')], { gap: 'space.3' },
  ({ props, children }: RenderInput) => <div style={{ display: 'flex', flexDirection: 'column', gap: C(props.gap) }}>{children}</div>, { container: true });
mk('Layout', 'spacer', 'Spacer', 'Empty vertical space.', 'MoveVertical', [sp('size', 'Size')], { size: 'space.6' },
  ({ props }: RenderInput) => <div aria-hidden style={{ height: C(props.size) }} />, { motion: false });
mk('Layout', 'divider', 'Divider', 'A horizontal rule.', 'Minus', [col('color', 'Color'), sp('margin', 'Margin')], { color: 'color.outline', margin: 'space.3' },
  ({ props }: RenderInput) => <hr style={{ border: 'none', borderTop: `1px solid ${C(props.color)}`, margin: `${C(props.margin)} 0` }} />, { motion: false, role: 'separator' });
mk('Layout', 'card', 'Card', 'A surface container with padding + radius.', 'CreditCard', [sp('pad', 'Padding'), col('bg', 'Background'), sel('radius', 'Radius', ['radius.sm', 'radius.md', 'radius.lg', 'radius.xl']), bl('shadow', 'Shadow')], { pad: 'space.4', bg: 'color.surface', radius: 'radius.md', shadow: true },
  ({ props, children }: RenderInput) => <div style={{ padding: C(props.pad), background: C(props.bg), borderRadius: C(props.radius), border: `1px solid ${tok('color.outline')}`, boxShadow: b(props.shadow) ? tok('shadow.md') : 'none' }}>{children}</div>, { container: true });

// ═══ CONTENT ═══
mk('Content', 'heading', 'Heading', 'A section title.', 'Heading', [t('text', 'Text'), sel('level', 'Level', ['h1', 'h2', 'h3']), col('color', 'Color')], { text: 'Heading', level: 'h2', color: 'color.onSurface' },
  ({ props }: RenderInput) => { const sz = { h1: 'font.2xl', h2: 'font.xl', h3: 'font.lg' }[s(props.level, 'h2')] || 'font.xl'; return <div style={{ fontSize: C(sz), fontWeight: 800, color: C(props.color), fontFamily: tok('font.family', 'inherit') }}>{s(props.text, 'Heading')}</div>; }, { role: 'heading' });
mk('Content', 'paragraph', 'Paragraph', 'A block of body text.', 'Pilcrow', [lt('text', 'Text'), col('color', 'Color')], { text: 'Body text goes here.', color: 'color.onSurfaceVariant' },
  ({ props }: RenderInput) => <p style={{ margin: 0, fontSize: tok('font.sm'), lineHeight: 1.6, color: C(props.color) }}>{s(props.text)}</p>);
mk('Content', 'richtext', 'Rich Text', 'Formatted multi-line rich text.', 'Text', [lt('html', 'Content')], { html: 'Rich <b>text</b> block.' },
  ({ props }: RenderInput) => <div style={{ fontSize: tok('font.sm'), lineHeight: 1.6, color: tok('color.onSurface') }} dangerouslySetInnerHTML={{ __html: s(props.html) }} />);
mk('Content', 'chip', 'Chip', 'A small rounded label.', 'Tag', [t('text', 'Text'), col('bg', 'Background'), col('color', 'Color')], { text: 'Chip', bg: 'color.surfaceHigh', color: 'color.onSurface' },
  ({ props }: RenderInput) => <span style={{ display: 'inline-block', padding: '4px 12px', borderRadius: tok('radius.full'), background: C(props.bg), color: C(props.color), fontSize: tok('font.xs'), fontWeight: 700 }}>{s(props.text, 'Chip')}</span>, { motion: false });
mk('Content', 'badge', 'Badge', 'A count / status badge.', 'BadgeCheck', [t('text', 'Text'), col('bg', 'Background')], { text: '3', bg: 'color.primary' },
  ({ props }: RenderInput) => <span style={{ display: 'inline-grid', placeItems: 'center', minWidth: 20, height: 20, padding: '0 6px', borderRadius: tok('radius.full'), background: C(props.bg), color: tok('color.onPrimary'), fontSize: 10, fontWeight: 800 }}>{s(props.text, '3')}</span>, { motion: false });
mk('Content', 'avatar', 'Avatar', 'A circular user image.', 'CircleUser', [url('src', 'Image URL'), num('size', 'Size')], { src: 'https://haatnow.app/icon-192.png', size: 48 },
  ({ props }: RenderInput) => <img alt="avatar" src={s(props.src)} style={{ width: Number(props.size) || 48, height: Number(props.size) || 48, borderRadius: tok('radius.full'), objectFit: 'cover', border: `1px solid ${tok('color.outline')}` }} />);

// ═══ MEDIA ═══
mk('Media', 'image', 'Image', 'A responsive image.', 'Image', [url('src', 'Source'), sel('radius', 'Radius', ['radius.none', 'radius.md', 'radius.lg']), sel('fit', 'Fit', ['cover', 'contain'])], { src: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600', radius: 'radius.md', fit: 'cover' },
  ({ props }: RenderInput) => <img alt="" src={s(props.src)} style={{ width: '100%', maxWidth: '100%', borderRadius: C(props.radius), objectFit: s(props.fit, 'cover') as React.CSSProperties['objectFit'], display: 'block' }} />);
mk('Media', 'gallery', 'Gallery', 'A grid of images.', 'Images', [num('cols', 'Columns')], { cols: 3 },
  ({ props }: RenderInput) => <div style={{ display: 'grid', gridTemplateColumns: `repeat(${Number(props.cols) || 3},1fr)`, gap: tok('space.2') }}>{[0, 1, 2, 3, 4, 5].map(i => <div key={i} style={{ aspectRatio: '1', borderRadius: tok('radius.sm'), background: tok('color.surfaceHigh') }} />)}</div>);
mk('Media', 'carousel', 'Carousel', 'A horizontal scroll carousel.', 'GalleryHorizontalEnd', [num('items', 'Items')], { items: 4 },
  ({ props }: RenderInput) => <div style={{ display: 'flex', gap: tok('space.3'), overflowX: 'auto', paddingBottom: 6 }}>{Array.from({ length: Number(props.items) || 4 }).map((_, i) => <div key={i} style={{ flex: '0 0 60%', aspectRatio: '16/9', borderRadius: tok('radius.md'), background: tok('color.surfaceHigh') }} />)}</div>);
mk('Media', 'video', 'Video', 'A video player frame.', 'Video', [url('poster', 'Poster')], { poster: '' },
  ({ props }: RenderInput) => <div style={{ position: 'relative', width: '100%', aspectRatio: '16/9', borderRadius: tok('radius.md'), background: s(props.poster) ? `center/cover url(${s(props.poster)})` : tok('color.surfaceHigh'), display: 'grid', placeItems: 'center' }}><span style={{ width: 46, height: 46, borderRadius: tok('radius.full'), background: 'rgba(0,0,0,.5)', display: 'grid', placeItems: 'center', color: '#fff' }}>▶</span></div>);
mk('Media', 'lottie', 'Lottie Placeholder', 'A Lottie animation slot (reserved).', 'Sparkle', [t('name', 'Animation')], { name: 'confetti' },
  ({ props }: RenderInput) => <div style={{ ...surface, aspectRatio: '1', display: 'grid', placeItems: 'center', color: tok('color.onSurfaceVariant'), fontSize: tok('font.xs') }}>Lottie · {s(props.name, 'animation')}</div>);
mk('Media', 'rive', 'Rive Placeholder', 'A Rive animation slot (reserved).', 'Box', [t('name', 'Artboard')], { name: 'main' },
  ({ props }: RenderInput) => <div style={{ ...surface, aspectRatio: '1', display: 'grid', placeItems: 'center', color: tok('color.onSurfaceVariant'), fontSize: tok('font.xs') }}>Rive · {s(props.name, 'artboard')}</div>);
mk('Media', 'icon', 'Icon', 'A glyph icon.', 'Star', [t('glyph', 'Glyph'), num('size', 'Size'), col('color', 'Color')], { glyph: '★', size: 24, color: 'color.primary' },
  ({ props }: RenderInput) => <span style={{ fontSize: Number(props.size) || 24, color: C(props.color), lineHeight: 1 }}>{s(props.glyph, '★')}</span>, { motion: false });

// ═══ FORMS ═══
const field = (labelTxt: string, control: React.ReactNode) => <label style={{ display: 'grid', gap: 5, width: '100%' }}><span style={{ fontSize: tok('font.xs'), fontWeight: 700, color: tok('color.onSurfaceVariant') }}>{labelTxt}</span>{control}</label>;
const inputStyle: React.CSSProperties = { width: '100%', padding: '9px 11px', borderRadius: tok('radius.sm'), border: `1px solid ${tok('color.outline')}`, background: tok('color.surfaceHigh'), color: tok('color.onSurface'), fontSize: tok('font.sm') };
mk('Forms', 'form', 'Form', 'A form container.', 'ClipboardList', [sp('gap', 'Gap')], { gap: 'space.3' },
  ({ props, children }: RenderInput) => <form onSubmit={e => e.preventDefault()} style={{ display: 'grid', gap: C(props.gap) }}>{children}</form>, { container: true, role: 'form' });
mk('Forms', 'input', 'Input', 'A single-line text field.', 'TextCursorInput', [t('label', 'Label'), t('placeholder', 'Placeholder')], { label: 'Label', placeholder: 'Enter…' },
  ({ props }: RenderInput) => field(s(props.label, 'Label'), <input placeholder={s(props.placeholder)} style={inputStyle} />), { motion: false });
mk('Forms', 'textarea', 'Textarea', 'A multi-line text field.', 'FileText', [t('label', 'Label'), t('placeholder', 'Placeholder')], { label: 'Message', placeholder: 'Type…' },
  ({ props }: RenderInput) => field(s(props.label, 'Message'), <textarea placeholder={s(props.placeholder)} rows={3} style={{ ...inputStyle, resize: 'vertical' }} />), { motion: false });
mk('Forms', 'checkbox', 'Checkbox', 'A checkbox with a label.', 'CheckSquare', [t('label', 'Label'), bl('checked', 'Checked', 'Content')], { label: 'I agree', checked: false },
  ({ props }: RenderInput) => <label style={{ display: 'inline-flex', gap: 8, alignItems: 'center', fontSize: tok('font.sm'), color: tok('color.onSurface') }}><input type="checkbox" defaultChecked={b(props.checked)} />{s(props.label, 'Option')}</label>, { motion: false });
mk('Forms', 'radio', 'Radio', 'A radio group.', 'CircleDot', [t('options', 'Options (comma)')], { options: 'One,Two,Three' },
  ({ props }: RenderInput) => <div style={{ display: 'grid', gap: 6 }}>{s(props.options, 'One,Two').split(',').map((o, i) => <label key={i} style={{ display: 'inline-flex', gap: 8, alignItems: 'center', fontSize: tok('font.sm'), color: tok('color.onSurface') }}><input type="radio" name="rg" defaultChecked={i === 0} />{o.trim()}</label>)}</div>, { motion: false });
mk('Forms', 'switch', 'Switch', 'A toggle switch.', 'ToggleRight', [t('label', 'Label'), bl('on', 'On', 'Content')], { label: 'Enabled', on: true },
  ({ props }: RenderInput) => <label style={{ display: 'inline-flex', gap: 8, alignItems: 'center', fontSize: tok('font.sm'), color: tok('color.onSurface') }}><span style={{ width: 34, height: 20, borderRadius: 999, background: b(props.on) ? tok('color.primary') : tok('color.outline'), position: 'relative' }}><span style={{ position: 'absolute', top: 2, insetInlineStart: b(props.on) ? 16 : 2, width: 16, height: 16, borderRadius: 999, background: '#fff' }} /></span>{s(props.label, 'Toggle')}</label>, { motion: false });
mk('Forms', 'select', 'Select', 'A dropdown select.', 'ChevronDown', [t('label', 'Label'), t('options', 'Options (comma)')], { label: 'Choose', options: 'A,B,C' },
  ({ props }: RenderInput) => field(s(props.label, 'Choose'), <select style={inputStyle}>{s(props.options, 'A,B').split(',').map((o, i) => <option key={i}>{o.trim()}</option>)}</select>), { motion: false });
mk('Forms', 'search', 'Search', 'A search input.', 'Search', [t('placeholder', 'Placeholder')], { placeholder: 'Search…' },
  ({ props }: RenderInput) => <div style={{ ...inputStyle, display: 'flex', alignItems: 'center', gap: 8 }}><span style={{ opacity: .6 }}>⌕</span><input placeholder={s(props.placeholder, 'Search…')} style={{ border: 'none', background: 'transparent', color: 'inherit', outline: 'none', flex: 1 }} /></div>, { motion: false });
mk('Forms', 'otp', 'OTP', 'A one-time-code input.', 'KeyRound', [num('digits', 'Digits')], { digits: 6 },
  ({ props }: RenderInput) => <div style={{ display: 'flex', gap: 8 }}>{Array.from({ length: Number(props.digits) || 6 }).map((_, i) => <div key={i} style={{ width: 38, height: 46, borderRadius: tok('radius.sm'), border: `1px solid ${tok('color.outline')}`, display: 'grid', placeItems: 'center', background: tok('color.surfaceHigh'), color: tok('color.onSurface'), fontWeight: 800 }}>•</div>)}</div>, { motion: false });
mk('Forms', 'phone', 'Phone Input', 'A phone number field with country code.', 'Phone', [t('code', 'Code'), t('placeholder', 'Placeholder')], { code: '+20', placeholder: '10 0000 0000' },
  ({ props }: RenderInput) => <div style={{ ...inputStyle, display: 'flex', alignItems: 'center', gap: 8 }}><span style={{ fontWeight: 700 }}>{s(props.code, '+20')}</span><input placeholder={s(props.placeholder)} style={{ border: 'none', background: 'transparent', color: 'inherit', outline: 'none', flex: 1 }} /></div>, { motion: false });
mk('Forms', 'datepicker', 'Date Picker', 'A date input.', 'Calendar', [t('label', 'Label')], { label: 'Date' },
  ({ props }: RenderInput) => field(s(props.label, 'Date'), <input type="date" style={inputStyle} />), { motion: false });
mk('Forms', 'timepicker', 'Time Picker', 'A time input.', 'Clock', [t('label', 'Label')], { label: 'Time' },
  ({ props }: RenderInput) => field(s(props.label, 'Time'), <input type="time" style={inputStyle} />), { motion: false });
mk('Forms', 'fileupload', 'File Upload', 'A drag-and-drop upload zone.', 'Upload', [t('label', 'Label')], { label: 'Drop files or click to upload' },
  ({ props }: RenderInput) => <div style={{ ...surface, padding: tok('space.5'), borderStyle: 'dashed', textAlign: 'center', color: tok('color.onSurfaceVariant'), fontSize: tok('font.sm') }}>⬆ {s(props.label, 'Upload')}</div>, { motion: false });

// ═══ COMMERCE ═══
mk('Commerce', 'productcard', 'Product Card', 'A product with image, title, price.', 'ShoppingBag', [t('title', 'Title'), t('price', 'Price'), url('img', 'Image')], { title: 'Product', price: 'SAR 49', img: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400' },
  ({ props }: RenderInput) => <div style={{ ...surface, overflow: 'hidden', width: 190 }}><div style={{ aspectRatio: '4/3', background: `center/cover url(${s(props.img)})` }} /><div style={{ padding: tok('space.3') }}><div style={{ fontWeight: 700, fontSize: tok('font.sm') }}>{s(props.title, 'Product')}</div><div style={{ color: tok('color.primary'), fontWeight: 800, marginTop: 4 }}>{s(props.price, 'SAR 0')}</div></div></div>);
mk('Commerce', 'pricetag', 'Price Tag', 'A price with currency.', 'Tag', [t('amount', 'Amount'), t('currency', 'Currency')], { amount: '49', currency: 'SAR' },
  ({ props }: RenderInput) => <span style={{ fontWeight: 800, fontSize: tok('font.lg'), color: tok('color.onSurface') }}>{s(props.currency, 'SAR')} {s(props.amount, '0')}</span>, { motion: false });
mk('Commerce', 'rating', 'Rating', 'A star rating.', 'Star', [num('value', 'Value (0-5)')], { value: 4 },
  ({ props }: RenderInput) => <span style={{ color: tok('color.primary'), letterSpacing: 2 }}>{'★★★★★'.slice(0, Number(props.value) || 4)}<span style={{ color: tok('color.outline') }}>{'★★★★★'.slice(Number(props.value) || 4)}</span></span>, { motion: false });
mk('Commerce', 'pricing', 'Pricing Table', 'A tier pricing table.', 'Table', [t('tiers', 'Tiers (comma)')], { tiers: 'Basic,Pro,Team' },
  ({ props }: RenderInput) => <div style={{ display: 'grid', gridTemplateColumns: `repeat(${s(props.tiers, 'A,B').split(',').length},1fr)`, gap: tok('space.3') }}>{s(props.tiers, 'Basic,Pro').split(',').map((tier, i) => <div key={i} style={{ ...surface, padding: tok('space.4'), textAlign: 'center' }}><div style={{ fontWeight: 800 }}>{tier.trim()}</div><div style={{ fontSize: tok('font.xl'), fontWeight: 800, color: tok('color.primary'), margin: '8px 0' }}>${(i + 1) * 9}</div><div style={{ fontSize: tok('font.xs'), color: tok('color.onSurfaceVariant') }}>per month</div></div>)}</div>);
mk('Commerce', 'storebadge', 'Store Badge', 'App Store / Google Play badges.', 'Store', [sel('store', 'Store', ['App Store', 'Google Play'])], { store: 'App Store' },
  ({ props }: RenderInput) => <span style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '8px 16px', borderRadius: tok('radius.sm'), background: '#000', color: '#fff', fontSize: tok('font.sm'), fontWeight: 700 }}>{s(props.store) === 'Google Play' ? '▶' : ''} {s(props.store, 'App Store')}</span>, { motion: false });
mk('Commerce', 'appdownload', 'App Download', 'A dual store-badge download strip.', 'Download', [t('title', 'Title')], { title: 'Get the app' },
  ({ props }: RenderInput) => <div style={{ display: 'grid', gap: 10 }}><div style={{ fontWeight: 800 }}>{s(props.title, 'Get the app')}</div><div style={{ display: 'flex', gap: 8 }}>{['App Store', 'Google Play'].map(x => <span key={x} style={{ padding: '8px 14px', borderRadius: tok('radius.sm'), background: '#000', color: '#fff', fontSize: tok('font.xs'), fontWeight: 700 }}>{x}</span>)}</div></div>);

// ═══ NAVIGATION ═══
mk('Navigation', 'navbar', 'Navbar', 'A top navigation bar.', 'Menu', [t('brand', 'Brand'), t('links', 'Links (comma)')], { brand: 'HAAT', links: 'Home,Menu,About,Contact' },
  ({ props }: RenderInput) => <nav style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: `${tok('space.3')} ${tok('space.4')}`, background: tok('color.surface'), borderBottom: `1px solid ${tok('color.outline')}`, borderRadius: tok('radius.md') }}><span style={{ fontWeight: 800, color: tok('color.onSurface') }}>{s(props.brand, 'HAAT')}</span><span style={{ display: 'flex', gap: 16 }}>{s(props.links, 'Home,About').split(',').map((l, i) => <span key={i} style={{ fontSize: tok('font.sm'), color: tok('color.onSurfaceVariant') }}>{l.trim()}</span>)}</span></nav>, { role: 'navigation' });
mk('Navigation', 'sidebar', 'Sidebar', 'A vertical side navigation.', 'PanelLeft', [t('items', 'Items (comma)')], { items: 'Dashboard,Orders,Products,Settings' },
  ({ props }: RenderInput) => <div style={{ ...surface, width: 190, padding: tok('space.2'), display: 'grid', gap: 3 }}>{s(props.items, 'A,B').split(',').map((it, i) => <div key={i} style={{ padding: '8px 10px', borderRadius: tok('radius.sm'), background: i === 0 ? tok('color.surfaceHigh') : 'transparent', fontSize: tok('font.sm'), color: tok('color.onSurface') }}>{it.trim()}</div>)}</div>, { role: 'navigation' });
mk('Navigation', 'bottomnav', 'Bottom Navigation', 'A mobile bottom tab bar.', 'PanelBottom', [t('tabs', 'Tabs (comma)')], { tabs: 'Home,Search,Cart,Profile' },
  ({ props }: RenderInput) => <div style={{ display: 'flex', justifyContent: 'space-around', padding: tok('space.2'), background: tok('color.surface'), borderTop: `1px solid ${tok('color.outline')}`, borderRadius: tok('radius.md') }}>{s(props.tabs, 'Home,Profile').split(',').map((tb, i) => <div key={i} style={{ display: 'grid', placeItems: 'center', gap: 3, fontSize: 9, color: i === 0 ? tok('color.primary') : tok('color.onSurfaceVariant') }}><span style={{ width: 18, height: 18, borderRadius: 6, background: 'currentColor', opacity: .8 }} />{tb.trim()}</div>)}</div>, { role: 'navigation' });
mk('Navigation', 'tabs', 'Tabs', 'A tab strip.', 'AppWindow', [t('tabs', 'Tabs (comma)')], { tabs: 'Overview,Details,Reviews' },
  ({ props }: RenderInput) => <div style={{ display: 'flex', gap: 4, borderBottom: `1px solid ${tok('color.outline')}` }}>{s(props.tabs, 'A,B').split(',').map((tb, i) => <div key={i} style={{ padding: '8px 14px', fontSize: tok('font.sm'), fontWeight: 700, color: i === 0 ? tok('color.onSurface') : tok('color.onSurfaceVariant'), borderBottom: i === 0 ? `2px solid ${tok('color.primary')}` : '2px solid transparent' }}>{tb.trim()}</div>)}</div>, { role: 'tablist' });
mk('Navigation', 'fab', 'Floating Action Button', 'A floating action button.', 'Plus', [t('glyph', 'Glyph'), col('bg', 'Background')], { glyph: '+', bg: 'color.primary' },
  ({ props }: RenderInput) => <button style={{ width: 54, height: 54, borderRadius: tok('radius.full'), border: 'none', background: C(props.bg), color: tok('color.onPrimary'), fontSize: 24, fontWeight: 800, boxShadow: tok('shadow.lg'), cursor: 'pointer' }}>{s(props.glyph, '+')}</button>);
mk('Navigation', 'footer', 'Footer', 'A page footer.', 'PanelBottomClose', [t('text', 'Text')], { text: '© HAAT NOW' },
  ({ props }: RenderInput) => <footer style={{ padding: tok('space.5'), background: tok('color.surface'), borderTop: `1px solid ${tok('color.outline')}`, textAlign: 'center', color: tok('color.onSurfaceVariant'), fontSize: tok('font.xs'), borderRadius: tok('radius.md') }}>{s(props.text, '© HAAT NOW')}</footer>, { role: 'contentinfo' });

// ═══ MARKETING ═══
mk('Marketing', 'hero', 'Hero', 'A hero banner with title, subtitle, CTA.', 'Megaphone', [t('title', 'Title'), lt('subtitle', 'Subtitle'), t('cta', 'CTA'), col('bg', 'Background')], { title: 'Everything, delivered', subtitle: 'Food, groceries & more — one app.', cta: 'Order now', bg: 'color.surface' },
  ({ props }: RenderInput) => <div style={{ padding: tok('space.7'), borderRadius: tok('radius.lg'), background: C(props.bg), textAlign: 'center', display: 'grid', gap: 12, justifyItems: 'center' }}><div style={{ fontSize: tok('font.2xl'), fontWeight: 800, color: tok('color.onSurface') }}>{s(props.title, 'Title')}</div><div style={{ fontSize: tok('font.md'), color: tok('color.onSurfaceVariant'), maxWidth: 460 }}>{s(props.subtitle)}</div><button style={{ padding: '12px 28px', borderRadius: tok('radius.full'), border: 'none', background: tok('color.primary'), color: tok('color.onPrimary'), fontWeight: 800, cursor: 'pointer' }}>{s(props.cta, 'Get started')}</button></div>);
mk('Marketing', 'banner', 'Banner', 'A promo banner strip.', 'Flag', [t('text', 'Text'), col('bg', 'Background')], { text: 'Free delivery this week!', bg: 'color.primary' },
  ({ props }: RenderInput) => <div style={{ padding: `${tok('space.3')} ${tok('space.4')}`, borderRadius: tok('radius.md'), background: C(props.bg), color: tok('color.onPrimary'), fontWeight: 700, textAlign: 'center' }}>{s(props.text, 'Promo')}</div>);
mk('Marketing', 'cta', 'CTA', 'A call-to-action block.', 'MousePointerClick', [t('title', 'Title'), t('button', 'Button')], { title: 'Ready to start?', button: 'Sign up' },
  ({ props }: RenderInput) => <div style={{ ...surface, padding: tok('space.5'), display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 16, flexWrap: 'wrap' }}><div style={{ fontWeight: 800, fontSize: tok('font.lg') }}>{s(props.title, 'Ready?')}</div><button style={{ padding: '10px 22px', borderRadius: tok('radius.full'), border: 'none', background: tok('color.primary'), color: tok('color.onPrimary'), fontWeight: 800, cursor: 'pointer' }}>{s(props.button, 'Go')}</button></div>);
mk('Marketing', 'featuregrid', 'Feature Grid', 'A grid of feature cards.', 'Grid3x3', [num('cols', 'Columns')], { cols: 3 },
  ({ props }: RenderInput) => <div style={{ display: 'grid', gridTemplateColumns: `repeat(${Number(props.cols) || 3},1fr)`, gap: tok('space.3') }}>{['Fast', 'Secure', 'Simple'].map((f, i) => <div key={i} style={{ ...surface, padding: tok('space.4'), display: 'grid', gap: 8 }}><span style={{ width: 34, height: 34, borderRadius: tok('radius.sm'), background: tok('color.surfaceHigh'), display: 'grid', placeItems: 'center', color: tok('color.primary') }}>◆</span><div style={{ fontWeight: 800 }}>{f}</div><div style={{ fontSize: tok('font.xs'), color: tok('color.onSurfaceVariant') }}>Feature description.</div></div>)}</div>);
mk('Marketing', 'testimonials', 'Testimonials', 'Customer quotes.', 'Quote', [lt('quote', 'Quote'), t('author', 'Author')], { quote: '“Best delivery app I have used.”', author: 'A. Customer' },
  ({ props }: RenderInput) => <div style={{ ...surface, padding: tok('space.5') }}><div style={{ fontSize: tok('font.md'), fontStyle: 'italic', color: tok('color.onSurface') }}>{s(props.quote)}</div><div style={{ marginTop: 10, fontSize: tok('font.xs'), fontWeight: 700, color: tok('color.onSurfaceVariant') }}>— {s(props.author, 'Customer')}</div></div>);
mk('Marketing', 'team', 'Team', 'A team member grid.', 'Users', [num('count', 'Members')], { count: 3 },
  ({ props }: RenderInput) => <div style={{ display: 'flex', gap: tok('space.4'), flexWrap: 'wrap' }}>{Array.from({ length: Number(props.count) || 3 }).map((_, i) => <div key={i} style={{ display: 'grid', justifyItems: 'center', gap: 6 }}><span style={{ width: 64, height: 64, borderRadius: tok('radius.full'), background: tok('color.surfaceHigh') }} /><div style={{ fontSize: tok('font.xs'), fontWeight: 700 }}>Member {i + 1}</div></div>)}</div>);
mk('Marketing', 'countdown', 'Countdown', 'A countdown timer.', 'TimerReset', [], {},
  () => <div style={{ display: 'flex', gap: 8 }}>{['02', '11', '45', '09'].map((v, i) => <div key={i} style={{ ...surface, minWidth: 48, padding: '8px 6px', textAlign: 'center' }}><div style={{ fontSize: tok('font.lg'), fontWeight: 800, color: tok('color.primary') }}>{v}</div><div style={{ fontSize: 8, color: tok('color.onSurfaceVariant') }}>{['DAYS', 'HRS', 'MIN', 'SEC'][i]}</div></div>)}</div>);
mk('Marketing', 'statistics', 'Statistics', 'A row of headline stats.', 'BarChart3', [], {},
  () => <div style={{ display: 'flex', gap: tok('space.6'), flexWrap: 'wrap' }}>{[['10k+', 'Orders'], ['4.9★', 'Rating'], ['120', 'Cities']].map(([v, l], i) => <div key={i}><div style={{ fontSize: tok('font.xl'), fontWeight: 800, color: tok('color.primary') }}>{v}</div><div style={{ fontSize: tok('font.xs'), color: tok('color.onSurfaceVariant') }}>{l}</div></div>)}</div>);
mk('Marketing', 'faq', 'FAQ', 'A frequently-asked-questions list.', 'HelpCircle', [t('items', 'Questions (comma)')], { items: 'How to order?,Delivery time?,Refunds?' },
  ({ props }: RenderInput) => <div style={{ display: 'grid', gap: 8 }}>{s(props.items, 'Q1,Q2').split(',').map((q, i) => <div key={i} style={{ ...surface, padding: tok('space.3'), display: 'flex', justifyContent: 'space-between' }}><span style={{ fontSize: tok('font.sm'), fontWeight: 700 }}>{q.trim()}</span><span style={{ color: tok('color.onSurfaceVariant') }}>+</span></div>)}</div>);

// ═══ DASHBOARD ═══
mk('Dashboard', 'statcard', 'Stat Card', 'A KPI stat card.', 'Gauge', [t('label', 'Label'), t('value', 'Value'), t('delta', 'Delta')], { label: 'Revenue', value: 'SAR 84.2k', delta: '+12%' },
  ({ props }: RenderInput) => <div style={{ ...surface, padding: tok('space.4'), display: 'grid', gap: 4, minWidth: 150 }}><span style={{ fontSize: tok('font.xs'), color: tok('color.onSurfaceVariant') }}>{s(props.label, 'Metric')}</span><span style={{ fontSize: tok('font.xl'), fontWeight: 800, color: tok('color.onSurface') }}>{s(props.value, '0')}</span><span style={{ fontSize: tok('font.xs'), fontWeight: 700, color: tok('color.primary') }}>{s(props.delta, '')}</span></div>);
mk('Dashboard', 'kpirow', 'KPI Row', 'A row of KPI tiles.', 'LayoutDashboard', [], {},
  () => <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: tok('space.3') }}>{[['Orders', '312'], ['Revenue', 'SAR 84k'], ['AOV', 'SAR 63'], ['Refunds', '1.2%']].map(([l, v], i) => <div key={i} style={{ ...surface, padding: tok('space.3') }}><div style={{ fontSize: tok('font.xs'), color: tok('color.onSurfaceVariant') }}>{l}</div><div style={{ fontSize: tok('font.lg'), fontWeight: 800 }}>{v}</div></div>)}</div>);
mk('Dashboard', 'progress', 'Progress', 'A progress bar.', 'Loader', [num('value', 'Percent'), col('color', 'Color')], { value: 64, color: 'color.primary' },
  ({ props }: RenderInput) => <div style={{ width: '100%', height: 10, borderRadius: 999, background: tok('color.surfaceHigh'), overflow: 'hidden' }}><div style={{ width: `${Math.min(100, Number(props.value) || 0)}%`, height: '100%', background: C(props.color), borderRadius: 999 }} /></div>, { role: 'progressbar' });
mk('Dashboard', 'timeline', 'Timeline', 'A vertical activity timeline.', 'GitCommitHorizontal', [t('items', 'Steps (comma)')], { items: 'Placed,Preparing,On the way,Delivered' },
  ({ props }: RenderInput) => <div style={{ display: 'grid', gap: 0 }}>{s(props.items, 'A,B').split(',').map((it, i, a) => <div key={i} style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}><div style={{ display: 'grid', justifyItems: 'center' }}><span style={{ width: 12, height: 12, borderRadius: 999, background: i === 0 ? tok('color.primary') : tok('color.outline') }} />{i < a.length - 1 && <span style={{ width: 2, height: 22, background: tok('color.outline') }} />}</div><span style={{ fontSize: tok('font.sm'), color: tok('color.onSurface'), paddingTop: -2 }}>{it.trim()}</span></div>)}</div>);
mk('Dashboard', 'activity', 'Activity Feed', 'A list of recent activity.', 'Activity', [t('items', 'Items (comma)')], { items: 'New order #1042,Payout sent,Review received' },
  ({ props }: RenderInput) => <div style={{ display: 'grid', gap: 6 }}>{s(props.items, 'A,B').split(',').map((it, i) => <div key={i} style={{ ...surface, padding: tok('space.3'), display: 'flex', gap: 8, alignItems: 'center' }}><span style={{ width: 8, height: 8, borderRadius: 999, background: tok('color.primary') }} /><span style={{ fontSize: tok('font.sm') }}>{it.trim()}</span></div>)}</div>);

// ═══ CHARTS ═══
mk('Charts', 'barchart', 'Bar Chart', 'A simple bar chart.', 'BarChart3', [t('data', 'Values (comma)'), col('color', 'Color')], { data: '40,70,55,90,60,80', color: 'color.primary' },
  ({ props }: RenderInput) => { const d = s(props.data, '10,20').split(',').map(x => Number(x) || 0); const mx = Math.max(...d, 1); return <div style={{ display: 'flex', alignItems: 'flex-end', gap: 6, height: 120 }}>{d.map((v, i) => <div key={i} style={{ flex: 1, height: `${(v / mx) * 100}%`, background: C(props.color), borderRadius: '4px 4px 0 0', minWidth: 6 }} />)}</div>; }, { role: 'img' });
mk('Charts', 'linechart', 'Line Chart', 'A line/area chart.', 'LineChart', [t('data', 'Values (comma)'), col('color', 'Color')], { data: '20,45,30,60,50,80,70', color: 'color.primary' },
  ({ props }: RenderInput) => { const d = s(props.data, '10,20').split(',').map(x => Number(x) || 0); const mx = Math.max(...d, 1); const pts = d.map((v, i) => `${(i / (d.length - 1)) * 100},${100 - (v / mx) * 100}`).join(' '); return <svg viewBox="0 0 100 100" preserveAspectRatio="none" style={{ width: '100%', height: 120 }}><polyline points={pts} fill="none" stroke={C(props.color)} strokeWidth={2} vectorEffect="non-scaling-stroke" /></svg>; }, { role: 'img' });
mk('Charts', 'donut', 'Donut Chart', 'A donut / ring chart.', 'PieChart', [num('value', 'Percent'), col('color', 'Color')], { value: 68, color: 'color.primary' },
  ({ props }: RenderInput) => { const v = Math.min(100, Number(props.value) || 0); return <div style={{ width: 120, height: 120, borderRadius: '50%', background: `conic-gradient(${C(props.color)} ${v * 3.6}deg, ${tok('color.surfaceHigh')} 0)`, display: 'grid', placeItems: 'center' }}><div style={{ width: 78, height: 78, borderRadius: '50%', background: tok('color.background'), display: 'grid', placeItems: 'center', fontWeight: 800, color: tok('color.onSurface') }}>{v}%</div></div>; }, { role: 'img' });
mk('Charts', 'sparkline', 'Sparkline', 'A compact inline trend line.', 'TrendingUp', [t('data', 'Values (comma)'), col('color', 'Color')], { data: '3,5,4,6,5,8,7,9', color: 'color.primary' },
  ({ props }: RenderInput) => { const d = s(props.data, '1,2').split(',').map(x => Number(x) || 0); const mx = Math.max(...d, 1); const pts = d.map((v, i) => `${(i / (d.length - 1)) * 100},${100 - (v / mx) * 100}`).join(' '); return <svg viewBox="0 0 100 30" preserveAspectRatio="none" style={{ width: 120, height: 30 }}><polyline points={pts} fill="none" stroke={C(props.color)} strokeWidth={2} vectorEffect="non-scaling-stroke" /></svg>; }, { role: 'img' });

// ═══ MAPS ═══
mk('Maps', 'map', 'Map', 'A map view frame.', 'Map', [t('label', 'Label')], { label: 'Riyadh' },
  ({ props }: RenderInput) => <div style={{ position: 'relative', width: '100%', aspectRatio: '16/9', borderRadius: tok('radius.md'), overflow: 'hidden', background: 'linear-gradient(135deg,#1b2a24,#0e1713)', border: `1px solid ${tok('color.outline')}` }}><div style={{ position: 'absolute', inset: 0, backgroundImage: `linear-gradient(${tok('color.outline')} 1px,transparent 1px),linear-gradient(90deg,${tok('color.outline')} 1px,transparent 1px)`, backgroundSize: '28px 28px', opacity: .3 }} /><span style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%,-100%)', color: tok('color.primary'), fontSize: 26 }}>◉</span><span style={{ position: 'absolute', bottom: 8, insetInlineStart: 10, fontSize: tok('font.xs'), color: tok('color.onSurfaceVariant') }}>{s(props.label, 'Map')}</span></div>, { role: 'img' });
mk('Maps', 'locationpicker', 'Location Picker', 'A map with an address search.', 'MapPin', [t('placeholder', 'Placeholder')], { placeholder: 'Search address…' },
  ({ props }: RenderInput) => <div style={{ ...surface, overflow: 'hidden' }}><div style={{ ...inputStyle, borderRadius: 0, border: 'none', borderBottom: `1px solid ${tok('color.outline')}` }}>⌕ {s(props.placeholder, 'Search…')}</div><div style={{ aspectRatio: '16/9', background: 'linear-gradient(135deg,#1b2a24,#0e1713)', display: 'grid', placeItems: 'center', color: tok('color.primary'), fontSize: 26 }}>◉</div></div>);

// ═══ SOCIAL ═══
mk('Social', 'sociallinks', 'Social Links', 'A row of social icons.', 'Share2', [t('networks', 'Networks (comma)')], { networks: 'X,Instagram,TikTok,YouTube' },
  ({ props }: RenderInput) => <div style={{ display: 'flex', gap: 8 }}>{s(props.networks, 'X,IG').split(',').map((nw, i) => <span key={i} style={{ width: 34, height: 34, borderRadius: tok('radius.full'), background: tok('color.surfaceHigh'), display: 'grid', placeItems: 'center', fontSize: 10, fontWeight: 700, color: tok('color.onSurface') }}>{nw.trim().slice(0, 2)}</span>)}</div>);
mk('Social', 'sharebar', 'Share Bar', 'A share-to-social bar.', 'Forward', [], {},
  () => <div style={{ display: 'flex', gap: 8 }}>{['Share', 'Copy link', 'WhatsApp'].map((x, i) => <span key={i} style={{ padding: '6px 12px', borderRadius: tok('radius.full'), background: tok('color.surfaceHigh'), fontSize: tok('font.xs'), fontWeight: 700, color: tok('color.onSurface') }}>{x}</span>)}</div>);
mk('Social', 'followcard', 'Follow Card', 'A profile follow card.', 'UserPlus', [t('name', 'Name'), t('handle', 'Handle')], { name: 'HAAT NOW', handle: '@haatnow' },
  ({ props }: RenderInput) => <div style={{ ...surface, padding: tok('space.4'), display: 'flex', alignItems: 'center', gap: 12 }}><span style={{ width: 44, height: 44, borderRadius: tok('radius.full'), background: tok('color.surfaceHigh') }} /><div style={{ flex: 1 }}><div style={{ fontWeight: 800, fontSize: tok('font.sm') }}>{s(props.name, 'Name')}</div><div style={{ fontSize: tok('font.xs'), color: tok('color.onSurfaceVariant') }}>{s(props.handle, '@handle')}</div></div><button style={{ padding: '6px 16px', borderRadius: tok('radius.full'), border: 'none', background: tok('color.primary'), color: tok('color.onPrimary'), fontWeight: 800, fontSize: tok('font.xs'), cursor: 'pointer' }}>Follow</button></div>);

// ═══ AUTHENTICATION ═══
mk('Authentication', 'loginform', 'Login Form', 'A phone/OTP login form.', 'LogIn', [t('title', 'Title')], { title: 'Sign in' },
  ({ props }: RenderInput) => <div style={{ ...surface, padding: tok('space.5'), display: 'grid', gap: 12, maxWidth: 320 }}><div style={{ fontWeight: 800, fontSize: tok('font.lg') }}>{s(props.title, 'Sign in')}</div><div style={inputStyle}>+20 · phone number</div><button style={{ padding: '10px', borderRadius: tok('radius.sm'), border: 'none', background: tok('color.primary'), color: tok('color.onPrimary'), fontWeight: 800, cursor: 'pointer' }}>Send code</button></div>, { role: 'form' });
mk('Authentication', 'otpverify', 'OTP Verify', 'An OTP verification card.', 'ShieldCheck', [num('digits', 'Digits')], { digits: 6 },
  ({ props }: RenderInput) => <div style={{ ...surface, padding: tok('space.5'), display: 'grid', gap: 12, justifyItems: 'center' }}><div style={{ fontWeight: 800 }}>Enter the code</div><div style={{ display: 'flex', gap: 6 }}>{Array.from({ length: Number(props.digits) || 6 }).map((_, i) => <div key={i} style={{ width: 34, height: 42, borderRadius: tok('radius.sm'), border: `1px solid ${tok('color.outline')}`, display: 'grid', placeItems: 'center', color: tok('color.onSurface') }}>•</div>)}</div></div>, { role: 'form' });
mk('Authentication', 'signupform', 'Signup Form', 'A registration form.', 'UserPlus', [t('title', 'Title')], { title: 'Create account' },
  ({ props }: RenderInput) => <div style={{ ...surface, padding: tok('space.5'), display: 'grid', gap: 10, maxWidth: 320 }}><div style={{ fontWeight: 800, fontSize: tok('font.lg') }}>{s(props.title, 'Create account')}</div><div style={inputStyle}>Full name</div><div style={inputStyle}>Phone</div><button style={{ padding: '10px', borderRadius: tok('radius.sm'), border: 'none', background: tok('color.primary'), color: tok('color.onPrimary'), fontWeight: 800, cursor: 'pointer' }}>Register</button></div>, { role: 'form' });
mk('Authentication', 'socialauth', 'Social Auth', 'Social sign-in buttons.', 'Fingerprint', [], {},
  () => <div style={{ display: 'grid', gap: 8, maxWidth: 320 }}>{['Continue with Apple', 'Continue with Google'].map((x, i) => <button key={i} style={{ padding: '10px', borderRadius: tok('radius.sm'), border: `1px solid ${tok('color.outline')}`, background: tok('color.surfaceHigh'), color: tok('color.onSurface'), fontWeight: 700, fontSize: tok('font.sm'), cursor: 'pointer' }}>{x}</button>)}</div>);

// ═══ UTILITIES ═══
mk('Utilities', 'button', 'Button', 'A primary button.', 'MousePointer', [t('label', 'Label'), col('bg', 'Background'), col('color', 'Text'), sel('radius', 'Radius', ['radius.sm', 'radius.md', 'radius.full']), sel('size', 'Size', ['sm', 'md', 'lg'])], { label: 'Button', bg: 'color.primary', color: 'color.onPrimary', radius: 'radius.full', size: 'md' },
  ({ props }: RenderInput) => { const pad = { sm: '7px 16px', md: '11px 24px', lg: '14px 34px' }[s(props.size, 'md')] || '11px 24px'; return <button style={{ padding: pad, borderRadius: C(props.radius), border: 'none', background: C(props.bg), color: C(props.color), fontWeight: 800, fontSize: tok('font.sm'), cursor: 'pointer' }}>{s(props.label, 'Button')}</button>; }, { role: 'button' });
mk('Utilities', 'iconbutton', 'Icon Button', 'A compact icon button.', 'CirclePlus', [t('glyph', 'Glyph'), col('bg', 'Background')], { glyph: '+', bg: 'color.surfaceHigh' },
  ({ props }: RenderInput) => <button style={{ width: 40, height: 40, borderRadius: tok('radius.full'), border: `1px solid ${tok('color.outline')}`, background: C(props.bg), color: tok('color.onSurface'), fontSize: 18, cursor: 'pointer' }}>{s(props.glyph, '+')}</button>, { role: 'button' });
mk('Utilities', 'accordion', 'Accordion', 'A collapsible section list.', 'ChevronsUpDown', [t('items', 'Items (comma)')], { items: 'Section one,Section two,Section three' },
  ({ props }: RenderInput) => <div style={{ display: 'grid', gap: 6 }}>{s(props.items, 'A,B').split(',').map((it, i) => <div key={i} style={{ ...surface, padding: tok('space.3'), display: 'flex', justifyContent: 'space-between' }}><span style={{ fontWeight: 700, fontSize: tok('font.sm') }}>{it.trim()}</span><span style={{ color: tok('color.onSurfaceVariant') }}>{i === 0 ? '▾' : '▸'}</span></div>)}</div>);
mk('Utilities', 'qrcode', 'QR Code', 'A QR code placeholder.', 'QrCode', [num('size', 'Size')], { size: 120 },
  ({ props }: RenderInput) => { const S2 = Number(props.size) || 120; return <div style={{ width: S2, height: S2, background: '#fff', borderRadius: tok('radius.sm'), padding: 8 }}><div style={{ width: '100%', height: '100%', backgroundImage: 'repeating-conic-gradient(#000 0% 25%, #fff 0% 50%)', backgroundSize: '16px 16px' }} /></div>; }, { motion: false });
mk('Utilities', 'tooltip', 'Tooltip', 'A hover tooltip.', 'MessageSquare', [t('text', 'Text')], { text: 'Tooltip text' },
  ({ props }: RenderInput) => <span style={{ display: 'inline-block', padding: '6px 10px', borderRadius: tok('radius.sm'), background: tok('color.onSurface'), color: tok('color.background'), fontSize: tok('font.xs'), fontWeight: 600 }}>{s(props.text, 'Tooltip')}</span>);
mk('Utilities', 'popover', 'Popover', 'A floating popover panel.', 'MessageCircle', [lt('text', 'Content')], { text: 'Popover content goes here.' },
  ({ props }: RenderInput) => <div style={{ ...surface, padding: tok('space.3'), maxWidth: 220, boxShadow: tok('shadow.md'), fontSize: tok('font.sm') }}>{s(props.text)}</div>);

// ═══ FEEDBACK ═══
mk('Feedback', 'toast', 'Toast', 'A transient toast message.', 'Bell', [t('text', 'Text'), sel('kind', 'Kind', ['info', 'success', 'error'])], { text: 'Saved successfully', kind: 'success' },
  ({ props }: RenderInput) => { const c = { info: 'color.primary', success: 'color.primary', error: 'color.tertiary' }[s(props.kind, 'info')] || 'color.primary'; return <div style={{ ...surface, padding: '10px 14px', display: 'inline-flex', alignItems: 'center', gap: 8, boxShadow: tok('shadow.md') }}><span style={{ width: 8, height: 8, borderRadius: 999, background: C(c) }} /><span style={{ fontSize: tok('font.sm') }}>{s(props.text, 'Notice')}</span></div>; }, { role: 'status' });
mk('Feedback', 'modal', 'Modal', 'A centered modal dialog.', 'Square', [t('title', 'Title'), lt('body', 'Body')], { title: 'Confirm', body: 'Are you sure?' },
  ({ props }: RenderInput) => <div style={{ ...surface, padding: tok('space.5'), maxWidth: 340, boxShadow: tok('shadow.lg') }}><div style={{ fontWeight: 800, fontSize: tok('font.lg') }}>{s(props.title, 'Modal')}</div><div style={{ marginTop: 8, fontSize: tok('font.sm'), color: tok('color.onSurfaceVariant') }}>{s(props.body)}</div><div style={{ marginTop: 16, display: 'flex', gap: 8, justifyContent: 'flex-end' }}><button style={{ padding: '8px 16px', borderRadius: tok('radius.sm'), border: `1px solid ${tok('color.outline')}`, background: 'transparent', color: tok('color.onSurface'), cursor: 'pointer' }}>Cancel</button><button style={{ padding: '8px 16px', borderRadius: tok('radius.sm'), border: 'none', background: tok('color.primary'), color: tok('color.onPrimary'), fontWeight: 700, cursor: 'pointer' }}>Confirm</button></div></div>, { role: 'dialog' });
mk('Feedback', 'drawer', 'Drawer', 'A slide-in side drawer.', 'PanelRightOpen', [t('title', 'Title')], { title: 'Menu' },
  ({ props }: RenderInput) => <div style={{ ...surface, width: 240, padding: tok('space.4'), boxShadow: tok('shadow.lg') }}><div style={{ fontWeight: 800 }}>{s(props.title, 'Drawer')}</div><div style={{ marginTop: 12, display: 'grid', gap: 8 }}>{['Item one', 'Item two', 'Item three'].map((x, i) => <div key={i} style={{ padding: '8px 10px', borderRadius: tok('radius.sm'), background: tok('color.surfaceHigh'), fontSize: tok('font.sm') }}>{x}</div>)}</div></div>, { role: 'dialog' });
mk('Feedback', 'emptystate', 'Empty State', 'A no-data empty state.', 'Inbox', [t('title', 'Title'), lt('text', 'Text')], { title: 'Nothing here yet', text: 'Add your first item to get started.' },
  ({ props }: RenderInput) => <div style={{ ...surface, padding: tok('space.7'), textAlign: 'center', display: 'grid', gap: 8, justifyItems: 'center' }}><span style={{ width: 48, height: 48, borderRadius: tok('radius.md'), background: tok('color.surfaceHigh'), display: 'grid', placeItems: 'center', fontSize: 22 }}>∅</span><div style={{ fontWeight: 800 }}>{s(props.title, 'Empty')}</div><div style={{ fontSize: tok('font.sm'), color: tok('color.onSurfaceVariant') }}>{s(props.text)}</div></div>);
mk('Feedback', 'loading', 'Loading', 'A spinner loading indicator.', 'Loader2', [col('color', 'Color')], { color: 'color.primary' },
  ({ props }: RenderInput) => <div style={{ display: 'grid', placeItems: 'center', padding: tok('space.5') }}><span style={{ width: 30, height: 30, borderRadius: '50%', border: `3px solid ${tok('color.outline')}`, borderTopColor: C(props.color), display: 'inline-block', animation: 'cp-spin 0.8s linear infinite' }} /><style>{'@keyframes cp-spin{to{transform:rotate(360deg)}}'}</style></div>, { role: 'status' });
mk('Feedback', 'skeleton', 'Skeleton', 'A skeleton loading placeholder.', 'RectangleHorizontal', [num('lines', 'Lines')], { lines: 3 },
  ({ props }: RenderInput) => <div style={{ display: 'grid', gap: 8 }}>{Array.from({ length: Number(props.lines) || 3 }).map((_, i) => <div key={i} style={{ height: 12, width: `${100 - i * 12}%`, borderRadius: 6, background: `linear-gradient(90deg, ${tok('color.surfaceHigh')}, ${tok('color.outline')}, ${tok('color.surfaceHigh')})`, backgroundSize: '200% 100%', animation: 'cp-shimmer 1.4s ease infinite' }} />)}<style>{'@keyframes cp-shimmer{0%{background-position:200% 0}100%{background-position:-200% 0}}'}</style></div>, { role: 'status' });
mk('Feedback', 'errorstate', 'Error State', 'An error message state.', 'TriangleAlert', [t('title', 'Title'), lt('text', 'Text')], { title: 'Something went wrong', text: 'Please try again.' },
  ({ props }: RenderInput) => <div style={{ ...surface, padding: tok('space.6'), textAlign: 'center', display: 'grid', gap: 8, justifyItems: 'center', borderColor: 'rgba(255,107,107,.4)' }}><span style={{ fontSize: 26, color: '#ff6b6b' }}>⚠</span><div style={{ fontWeight: 800 }}>{s(props.title, 'Error')}</div><div style={{ fontSize: tok('font.sm'), color: tok('color.onSurfaceVariant') }}>{s(props.text)}</div></div>);
mk('Feedback', 'alert', 'Alert', 'An inline alert banner.', 'Info', [t('text', 'Text'), sel('kind', 'Kind', ['info', 'warning', 'error'])], { text: 'Heads up — this is an alert.', kind: 'info' },
  ({ props }: RenderInput) => { const c = { info: 'color.primary', warning: 'color.tertiary', error: 'color.tertiary' }[s(props.kind, 'info')] || 'color.primary'; return <div style={{ padding: '10px 14px', borderRadius: tok('radius.md'), background: tok('color.surfaceHigh'), borderInlineStart: `3px solid ${C(c)}`, color: tok('color.onSurface'), fontSize: tok('font.sm') }}>{s(props.text, 'Alert')}</div>; });

// Register everything.
specs.forEach(registerComponent);
